language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
before_deploy: echo 'ready to deploy?'
deploy:
- provider: releases
  api_key:
    secure: o+rKD1Qwd/A7yFAw1zYxta6Y8oXSHYpft67WzIp+44vvW4arMYZ3OyowuLwr5+Jes79Vkk9f5sSQsa+3BrrIwENX3fjTMHWhv4RwkudjCpLXK4Xb+tbaP0DgAlg9eQN4kP8pvPnwYBwopvu1sLZUeAEWOgVYfxFCExADpAuyAdg=
  file:
  - release/flora.min.js
  - release/flora.min.css
  on:
    repo: vinceallenvince/FloraJS
    tags: true
    all_branches: true
env:
  global:
    - GH_REF: github.com/vinceallenvince/Burner.git
    - secure: CipXlQpTaAirKaXn4fSKtVgCHg1NrzGi1vesa9iOzUOaTtQS+tn/BPnbZHt0/2tkHuIaW7XXX+5Y6OsaXI7icjoHBcS+J8GX1A4U3SqcrOQZ6ZKnyWaK8C67DZA1ezhCQEu9XfRPCPVpTtRkna9ctYcbodY3ekUoSujVrqMGU4w=
